### ISSUE TITLE
群晖报错找不到config

### ISSUE THREAD

**Issue by lclmiko** [SuperNG6/docker_aria2#12]
报错Configuration file /config/aria2.conf is not found.
然后就一直循环报错
配置了/config文件夹 硬盘上相应文件夹里面也有生成aria2.conf呀
docker注册表里面下载镜像安装的，难道还有地方没配置到？

**Comment by SuperNG6** [comment]
权限问题，你没有配置PUID，GUID

**Comment by lclmiko** [comment]
![image](https://user-images.githubusercontent.com/21024357/70335594-8b4b3b80-1882-11ea-8b87-55fff8c290f3.png)
配置了的

**Comment by lclmiko** [comment]
![捕获](https://user-images.githubusercontent.com/21024357/70336246-c601a380-1883-11ea-89cf-d8c5db91d1e6.JPG)
有配置啊

**Comment by SuperNG6** [comment]
关闭容器，把映射到群晖的文件夹删掉，新建容器试试

lclmiko <notifications@github.com>于2019年12月6日 周五下午11:55写道：

**Comment by lclmiko** [comment]
解决了
gpid要设为admin的101
谢谢

**Comment by SuperNG6** [comment]
不建议这样做，这样做就失去了usermapping意义了，你的文件将不可控，其他软件将很难对其进行操作
具体教程如图所示

![](https://github.com/SuperNG6/pic/blob/master/aria2/Xnip2019-12-07_10-35-24.png)

**Comment by lclmiko** [comment]
按照你给的方法操作这下没问题了
