### ISSUE TITLE
暂时只支持x86_64，期待以后支持arm&arm64

### ISSUE THREAD

**Issue by shanzhaozhen** [SuperNG6/docker_aria2#20]

**Comment by SuperNG6** [comment]
今天早上构建了，没有测试环境，不知道能否运行，希望能帮忙测试
docker pull superng6/aria2:arm64v8-latest
docker pull superng6/aria2:arm32v7-latest

````
docker run -d \
  --name=aria2 \
  -e PUID=1026 \
  -e PGID=100 \
  -e TZ=Asia/Shanghai \
  -e SECRET=yourtoken \
  -e UpdateTracker=true \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -p 6800:6800 \
  -v /path/to/appdata/config:/config \
  -v /path/to/downloads:/downloads \
  --restart unless-stopped \
  superng6/aria2:arm64v8-latest
````

**Comment by shanzhaozhen** [comment]
已经测试好了，可以正常运行，你在线构建的aria2的webui我觉得不太好使，还是建议整合到docker里面，为了简单化，统一把端口挂载在单一端口号我觉得会更好

**Comment by SuperNG6** [comment]
把webui放进容器了没有任何必要和好出，通讯端口为6800，是无论如何都需要暴露出来的，另外两个是为了加速下载。  
如果你觉得麻烦可能是因为我的webui仅支持https，http可以用这个   
http://sleele.gitee.io/ariang/#!/downloading
