### ISSUE TITLE
请问aria NG的在线页面RPC为啥使用HTTPS协议

### ISSUE THREAD

**Issue by tefiszx** [SuperNG6/docker_aria2#8]
![111](https://user-images.githubusercontent.com/20527882/68556550-abe3c980-046d-11ea-866d-f64e3e394493.jpg)

**Comment by SuperNG6** [comment]
加密，安全

tefiszx <notifications@github.com>于2019年11月11日 周一上午10:26写道：

**Comment by SuperNG6** [comment]
我在gitee上构建了支持http的版本  
http://sleele.gitee.io/ariang/#!/downloading
